//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public HoaDon()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> ID { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> VanChuyen { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
