//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int ID { get; set; }
        public int MaSP { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DanhGia { get; set; }
    
        public virtual User User { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
