//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.GioHangs = new HashSet<GioHang>();
            this.PhanHois = new HashSet<PhanHoi>();
            this.SuKiens = new HashSet<SuKien>();
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> MaDM { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual ICollection<PhanHoi> PhanHois { get; set; }
        public virtual ICollection<SuKien> SuKiens { get; set; }
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
