//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        public SuKien()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public int MaSK { get; set; }
        public string TenSK { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
